<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5491c155-e1e7-4d7f-b5fd-889d9f021e51</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/aside[1]/div[1]/ul[1]/li[4]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-menu-item\\ ant-menu-item-active\\ py-6\\ text-lg\\ "] &gt; [class="ant-menu-title-content"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:text=\\"My Profile\\"i"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>