<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4a3075e4-a9ae-4120-a9ea-ab41480a728f</elementGuidId>
    <imagePath></imagePath>
    <name>link_devGuildTrainingDevOpsTrainingBasic</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hover:text-[#26A9E0]"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/events/6697347c46152f13b96c95aa') and equals(@text,'[DevGuild] Training: DevOps Training - Basic')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link &gt;&gt; nth=4</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/events/6697347c46152f13b96c95aa</value>
        <webElementGuid>f9fdd4ed-010b-4667-a394-384c7228f937</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>[DevGuild] Training: DevOps Training - Basic</value>
        <webElementGuid>f9fdd4ed-010b-4667-a394-384c7228f937</webElementGuid>
    </webElementProperties>
</WebElementEntity>