<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>72eac03c-51d3-4ac6-a7cc-d643fa08af68</elementGuidId>
    <imagePath></imagePath>
    <name>div_whatIsEventifyWhoDevelops</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-select mb-2 md:mb-0 md:w-44 w-36 border-[#DEE1E6] h-[42px] font-sans css-1iz8u3y ant-select-single ant-select-show-arrow ant-select-open"] [class="ant-select-selection-item"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(4) &gt; div &gt; div &gt; form &gt; div:nth-child(2) &gt; .ant-row &gt; div &gt; .flex &gt; .ant-select &gt; .ant-select-selector &gt; .ant-select-selection-item &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>