<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>adf65c3a-8f31-4721-addf-62b090ebc2a1</elementGuidId>
    <imagePath></imagePath>
    <name>div_absolute5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="rounded-full h-[16px] w-[16px] mx-1.5 cursor-pointer  a                         bg-[#00B54980]a                         border-[3px] border-[#00B549] a                         delay-300 transition-[border] flex"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(5) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>