<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>40cfed4a-d758-48cc-b453-54344eee8495</elementGuidId>
    <imagePath></imagePath>
    <name>div_bannerMax3Mbupload</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-row pr-12 pt-2 css-1iz8u3y"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="What is Eventify?Who develops"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>