<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>659c564d-ecf6-4ba6-9345-08dbd391d039</elementGuidId>
    <imagePath></imagePath>
    <name>div_usersEvents71Phuoc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex items-center justify-between mx-auto text-blue-gray-900"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="UsersEvents75Phuoc"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>