<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fb566ace-3504-4964-83f7-1d44d738f9f0</elementGuidId>
    <imagePath></imagePath>
    <name>div_documentaries</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[6]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-select-item ant-select-item-option ant-select-item-option-active"] &gt; [class="ant-select-item-option-content"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[title="Documentaries"i] &gt;&gt; div</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>