<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c2d2d863-f9b7-4a65-85ee-25ad3490ed21</elementGuidId>
    <imagePath></imagePath>
    <name>image_avatar_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/span[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-row pl-2 py-1 hover:cursor-pointer css-12j6w01"]:nth-child(1) img</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.flex &gt; div &gt; div &gt; .ant-avatar &gt; img &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>