<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c97ea9a4-5ecd-41dd-b736-9f5c0dcad614</elementGuidId>
    <imagePath></imagePath>
    <name>image_avatar</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/span[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-row pl-2 py-1 hover:cursor-pointer css-1iz8u3y"]:nth-child(2) img</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; div &gt; .ant-avatar &gt; img</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>