<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4b95ae59-50cf-4058-9dbd-b3f037ab1b94</elementGuidId>
    <imagePath></imagePath>
    <name>button_save as draft</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[4]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-btn css-dqh9qm ant-btn-primary bg-[#27AAE1]"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Save as draft')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Save as draft"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Save as draft</value>
        <webElementGuid>010e999e-e9ce-4be2-be2c-f6b283b6f86f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>010e999e-e9ce-4be2-be2c-f6b283b6f86f</webElementGuid>
    </webElementProperties>
</WebElementEntity>