<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6e7b7517-e527-4121-b3a9-9a0b8f25581b</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-select-item ant-select-item-option ant-select-item-option-active"] &gt; [class="ant-select-item-option-content"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[title="400"i] &gt;&gt; div</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>