<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af42bb56-8337-4a11-a331-8cb3ab0b8240</elementGuidId>
    <imagePath></imagePath>
    <name>input_rc_select_0</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#rc_select_0</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'rc_select_0') and equals(@type,'search')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Search by employee code or"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>rc_select_0</value>
        <webElementGuid>1c6fac0c-3300-4e81-9213-85528144cb1b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>search</value>
        <webElementGuid>1c6fac0c-3300-4e81-9213-85528144cb1b</webElementGuid>
    </webElementProperties>
</WebElementEntity>