<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>05a48385-d666-4a43-a234-3f49c779237d</elementGuidId>
    <imagePath></imagePath>
    <name>td_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[7]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-picker-dropdown css-dqh9qm ant-picker-dropdown-placement-bottomLeft"]:nth-child(1) tr:nth-child(2) &gt; [class="ant-picker-cell ant-picker-cell-in-view"]:nth-child(7)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=cell[name="13"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>