<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1e9be73e-cf3d-4c11-97d1-8e009d495b62</elementGuidId>
    <imagePath></imagePath>
    <name>button_ok</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-picker-dropdown css-1fvgx0e ant-picker-dropdown-placement-topLeft"] [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'OK')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="OK"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>OK</value>
        <webElementGuid>bd0ce7dd-a0f4-441f-a784-65e062094520</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>bd0ce7dd-a0f4-441f-a784-65e062094520</webElementGuid>
    </webElementProperties>
</WebElementEntity>