<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e23fbc4c-0348-4ab3-943e-96f4170d4a2c</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/form[1]/div[1]/div[1]/div[2]/div[1]/div[1]/aside[1]/div[2]/ul[1]/li[3]/div[1]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="epr-emoji-category"]:nth-child(3) [type="button"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=listitem[name=\\"Smileys &amp; People\\"i] &gt;&gt; internal:label=\\"smile\\"s"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>f41dade5-b828-439c-805f-593f4882b461</webElementGuid>
    </webElementProperties>
</WebElementEntity>