<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8d4b1d63-e390-4a80-9678-a52fa241ef1a</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_10</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-steps-item ant-steps-item-wait ant-steps-item-custom"]:nth-child(5) &gt; [role="button"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Entry"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>