<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9b89363d-4fe2-4405-974d-03e0d243ffed</elementGuidId>
    <imagePath></imagePath>
    <name>input_title</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/form[1]/div[1]/div[1]/div[2]/div[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="title"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'title') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Add a name"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>title</value>
        <webElementGuid>5e03467e-4ecb-4d57-ac7f-642d6821fc86</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>5e03467e-4ecb-4d57-ac7f-642d6821fc86</webElementGuid>
    </webElementProperties>
</WebElementEntity>