<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
<description>Generated by Katalon AI</description>
    <elementGuidId>d7431240-38c1-4906-9e3d-a65fb6808ea4</elementGuidId>
    <imagePath></imagePath>
    <name>login_password</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//input[@id='txt-password-login']</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
</WebElementEntity>