<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>403aba26-5d31-45d5-b811-80df11e5ef80</elementGuidId>
    <imagePath></imagePath>
    <name>html_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//html</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>html</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>html</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>