<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aae9bc71-69e4-4d6f-8bf9-9ce34f6124db</elementGuidId>
    <imagePath></imagePath>
    <name>button_cell15</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-picker-dropdown css-dqh9qm ant-picker-dropdown-placement-bottomLeft"] [class="ant-picker-header-next-btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(5) &gt; .ant-picker-dropdown &gt; .ant-picker-panel-container &gt; .ant-picker-panel-layout &gt; .ant-picker-panel &gt; .ant-picker-date-panel &gt; .ant-picker-header &gt; .ant-picker-header-next-btn</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>b718ad1d-efc7-4859-94b4-787b53e55011</webElementGuid>
    </webElementProperties>
</WebElementEntity>