<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dd2937c5-3a65-4c34-910e-890174def16c</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[1]/div[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-btn css-dqh9qm ant-btn-default ant-btn-lg ant-btn-icon-only bg-white border-[#9095A1]"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section &gt;&gt; internal:has-text="Published EventsAll+"i &gt;&gt; internal:role=button &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>2e64e2f8-b9de-4ed1-9691-142e3842a3b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>