<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8564e2d6-accc-4fe9-ab6c-5ef4e8c249bf</elementGuidId>
    <imagePath></imagePath>
    <name>button_information</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="justify-center min-w-[136px] inline-flex items-center pl-1 py-4 pr-4 border-t-2 border-transparent hover:font-bold hover:cursor-pointer"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Information')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Information"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Information</value>
        <webElementGuid>010e999e-e9ce-4be2-be2c-f6b283b6f86f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>010e999e-e9ce-4be2-be2c-f6b283b6f86f</webElementGuid>
    </webElementProperties>
</WebElementEntity>