<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>151e2541-0ec9-488f-a6b3-ceca64d024b7</elementGuidId>
    <imagePath></imagePath>
    <name>button_addNew</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/table[1]/thead[1]/tr[1]/th[7]/div[1]/a[1]/button[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="rounded-md h-[25px]  hover:bg-[#d0d1d6] flex flex-row items-center  text-white font-medium p-1 cursor-pointer"] &gt; #Flat</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=columnheader[name="Add New"i] &gt;&gt; internal:role=link &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>