<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>76358a40-7445-4938-befc-845fdaeb631c</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_new</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/table[1]/thead[1]/tr[1]/th[7]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="rounded-md\\ flex\\ flex-row\\ items-center\\ lg\\:gap-2\\ font-medium\\ px-2\\ h-\\[25px\\]\\ \\ text-white\\ bg-\\[\\#3067E9\\]\\ hover\\:bg-\\[\\#2654c0\\]\\ cursor-pointer"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Add New')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Add New"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add New</value>
        <webElementGuid>1c42949e-7d4b-4e33-a2cc-4a858e33eee7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>1c42949e-7d4b-4e33-a2cc-4a858e33eee7</webElementGuid>
    </webElementProperties>
</WebElementEntity>