<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2da12ee7-9609-4a41-aab8-4a6061b01081</elementGuidId>
    <imagePath></imagePath>
    <name>button_my_events</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-btn\\ css-dqh9qm\\ ant-btn-primary\\ ant-btn-lg\\ flex\\ items-center\\ justify-between\\ rounded-md\\ hover\\:-translate-y-2\\ hover\\:shadow-l\\ transition\\ md\\:flex-1\\ min-w-\\[200px\\]\\ max-w-\\[440px\\]\\ w-\\[440px\\]"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'My Events \u2192')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="My Events \u2192"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>My Events →</value>
        <webElementGuid>1479594f-510a-4569-99d7-db2839f6c020</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>1479594f-510a-4569-99d7-db2839f6c020</webElementGuid>
    </webElementProperties>
</WebElementEntity>