<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>38792e73-7b5c-43fa-8900-063b58bcd30b</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-modal-wrap"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text="Administrative EventsPending+300HostPendingtest draft by ky huynhThu, April 11 | 10:00 AMhcmPhuoc Duy Nguyen+100PendingSE-278 Submit after Save as draftThu, April 04 | 10:00 AMSE-278 Submit after Save as draftDung Hoang Nguyen+100Pending[HAPPY DAY] "POM FRESH JUICE" IN YOUR AREAWed, April 03 | 10:00 AMCoffee Lounge, Tan Vien OfficeThy Thi Anh Phung+200PendingTEST REALTIME NOTIFYSun, March 31 | 10:00 AMnowhereTruong Huy Phan+100PendingSE-206(1-7): Dates are not the sameSat, March 30 | 12:00 PMSE-206(1-7): Dates are not the sameDung Hoang Nguyen+100Pending26/03Sat, March 30 | 10:00 AMnowhereAnh Nhat Van Duong12345•••"i &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>