<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>36bcc5be-488b-4e32-b9e1-8662c8948260</elementGuidId>
    <imagePath></imagePath>
    <name>div_selectEmail</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-select ant-select-lg col-span-3 w-10/12 custom-select  css-ncj747 ant-select-multiple ant-select-show-arrow ant-select-open ant-select-show-search"] [class="ant-select-selection-overflow"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#rc-tabs-0-panel-2 &gt; div &gt; .top-0 &gt; div:nth-child(3) &gt; .mb-2 &gt; .flex-col &gt; .ant-select &gt; .ant-select-selector &gt; .ant-select-selection-overflow</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>