<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff621a4b-3623-4fd0-96f7-80789bebb94b</elementGuidId>
    <imagePath></imagePath>
    <name>div_administrativeEventsAll100PendingFlashTeam</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[2]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-modal-content"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Administrative EventsAll+100PendingFlash - Team Building June 15Sat, June 08 | 10:00 AMVinh Hy+200HostApprovedVA to test#286Sat, June 08 | 10:00 AMHCMCKMS Technology, KMS Software+100ApprovedVA to test Custom Fields (sprint 21 demo)Fri, June 07 | 10:00 AMHCMC+200Approvedtest eventy1i12Fri, May 31 | 10:00 AMhcm+100ParticipantsApprovedCopied of VA to test #316Fri, May 31 | 10:00 AMHCMC+100ParticipantsApprovedVA to test #316Wed, May 29 | 10:00 AMHCMC12345•••"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>