<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c7cbb165-d8ea-45e1-b607-e55912d57323</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_23</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-modal-wrap"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text="Administrative EventsAll+300ApprovedHappen DateSat, April 20 | 10:00 AMHappen Date+100Approvedtrue testSat, April 13 | 10:00 AMaa+100ApprovedCopied of true test 01Sat, April 13 | 10:00 AMaa+100ApprovedCopied of Copied of true test 02Sat, April 13 | 10:00 AMaa+100ApprovedCopied of Copied of Copied of Copied of true test 04Sat, April 13 | 10:00 AMaa+100ApprovedCopied of true test 05Sat, April 13 | 10:00 AMaa12345•••"i &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>