<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fc4dd5bd-194f-47b5-b01f-24624dc16fbd</elementGuidId>
    <imagePath></imagePath>
    <name>dropdown_monthMay</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[11]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-select ant-select-sm ant-picker-calendar-month-select css-ncj747 ant-select-single ant-select-show-arrow ant-select-open"] [class="ant-select-selection-item"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span &gt;&gt; internal:has-text="May"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>