<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>db1382d9-4d99-481e-bbd9-0af30d95313f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_notify_via_mail</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/button[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex\\ flex-row\\ justify-start\\ flex-nowrap\\ p-2\\ hover\\:bg-gray-200\\ \\ text-black\\ \\ \\ hover\\:text-\\[\\#26A9E0\\]\\ hover\\:font-bold\\ truncate\\ "]:nth-child(3) &gt; [class="block\\ \\ \\ text-sm\\ text-center\\ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Notify via mail')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Notify via mail"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Notify via mail</value>
        <webElementGuid>1479594f-510a-4569-99d7-db2839f6c020</webElementGuid>
    </webElementProperties>
</WebElementEntity>