<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ef7f811e-fc0c-45d2-936c-d55d1bf241f9</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_400hostdraftdraft 1231231231sat</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid-card"] &gt; div:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+400HostDraftDraft 1231231231Sat, April 13 | 10:00 AMasdflaskdfjThy Thi Anh Phung')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +400 Host"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+400
        
        Host
        
        Draft
        
        Draft 1231231231
        
        Sat, April 13 | 10:00 AM
        
        asdflaskdfj
        Thy Thi Anh Phung</value>
        <webElementGuid>010e999e-e9ce-4be2-be2c-f6b283b6f86f</webElementGuid>
    </webElementProperties>
</WebElementEntity>