<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dce715cd-06cc-4fb1-9d30-4c208521871d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_host_pending_delete_admin_start</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nHost\n\nPending\n\nDelete Admin\n\nStart\n\nWed, Feb 28 | 12:00 AM\n\nEnd\n\nThu, Feb 29 | 11:59 PM\n\nDelete Admin')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Host
        
        Pending
        
        Delete Admin
        
        Start
        
        Wed, Feb 28 | 12:00 AM
        
        End
        
        Thu, Feb 29 | 11:59 PM
        
        Delete Admin</value>
        <webElementGuid>09ed0195-021b-4230-ad83-98a866fb7e7d</webElementGuid>
    </webElementProperties>
</WebElementEntity>