<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c84fb4a6-7c04-4037-8ef8-9c027c5ed00f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_pl - kms meeting 03251126view more →</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/div[2]/div[1]/div[5]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="slick-slide slick-active slick-current"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'PL - KMS Meeting 03251126View more →')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="PL - KMS Meeting 03251126"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>PL - KMS Meeting 03251126
        
        View more →</value>
        <webElementGuid>3836cc61-e237-47d9-9faa-f478a61a86d0</webElementGuid>
    </webElementProperties>
</WebElementEntity>