<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b721743c-bdf2-48a1-9748-3b158e4951fb</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_300hostapprovedhost5wed april </name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[6]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid-card"] &gt; div:nth-child(6) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+300HostApprovedHOST5Wed, April 10 | 10:00 AMasdasdKMS Technology, KMS Software, Organization Communication')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +300 Host check Approved HOST5 calendar Wed, April 10 | 10:00"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+300
        
        Host
        
        Approved
        
        HOST5
        
        Wed, April 10 | 10:00 AM
        
        asdasd
        KMS Technology, KMS Software, Organization Communication</value>
        <webElementGuid>eee8f410-af2e-4401-8656-e97b5b578062</webElementGuid>
    </webElementProperties>
</WebElementEntity>