<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cffcf987-6b5c-493a-91ec-2b322663e233</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_300hostapprovedhappen datesat </name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[4]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid grid-cols-1 landingCard:grid-cols-4 grid-rows-2 2xl:grid-cols-4 gap-[24px] lg:gap-[16px] xl:gap-[20px] 2xl:gap-[24px] mt-[24px] mx-auto transition"] &gt; div:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+300HostApprovedHappen DateSat, April 20 | 10:00 AMHappen Date')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +300 check Approved Happen Date calendar Sat, April 20 | 10:00"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+300
        
        Host
        
        Approved
        
        Happen Date
        
        Sat, April 20 | 10:00 AM
        
        Happen Date</value>
        <webElementGuid>eee8f410-af2e-4401-8656-e97b5b578062</webElementGuid>
    </webElementProperties>
</WebElementEntity>