<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e87b5cd2-f195-4d1d-8ddd-3c581e8873f3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100hostapprovedtrue testsat ap</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100HostApprovedtrue testSat, April 13 | 10:00 AMaa')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 Host check Approved true test calendar Sat, April 13 | 10"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Host
        
        Approved
        
        true test
        
        Sat, April 13 | 10:00 AM
        
        aa</value>
        <webElementGuid>105b4047-a6e2-4c25-a2d6-8edcec2138bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>