<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e441e5d4-48c6-4cad-88d1-a90ea368be45</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100hostapprovedtest visibilityf</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid-card"] &gt; div:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100HostApprovedTest visibilityFri, April 12 | 10:00 AMHCMCKMS Technology')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=dialog &gt;&gt; internal:role=link[name="event_banner.png +100 Host check Approved Test visibility calendar Fri, April"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Host
        
        Approved
        
        Test visibility
        
        Fri, April 12 | 10:00 AM
        
        HCMC
        KMS Technology</value>
        <webElementGuid>eee8f410-af2e-4401-8656-e97b5b578062</webElementGuid>
    </webElementProperties>
</WebElementEntity>