<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8b0813e2-1bc3-4168-9cf3-893aa33a0700</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100test visibilityfri april 12  1_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-child(7) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100Test visibilityFri, April 12 | 10:00 AMHCMC')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 Test"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Test visibility
        
        Fri, April 12 | 10:00 AM
        
        HCMC</value>
        <webElementGuid>2e64e2f8-b9de-4ed1-9691-142e3842a3b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>