<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>51cf96fc-84d4-4478-9a80-beb36336e404</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_host_approved_happen_2_wed_mar</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(2) &gt; [class="xl\\:w-\\[396px\\]\\ w-\\[440px\\]\\ xl\\:mx-2\\ mx-12"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nHost\n\nApproved\n\nHappen 2\n\nWed, March 27 | 08:30 AM\n\nHappen 2\nDung Hoang Nguyen')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 check Approved Happen 2 calendar N/A | N/A Happen 2 team"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Host
        
        Approved
        
        Happen 2
        
        Wed, March 27 | 08:30 AM
        
        Happen 2
        Dung Hoang Nguyen</value>
        <webElementGuid>1c42949e-7d4b-4e33-a2cc-4a858e33eee7</webElementGuid>
    </webElementProperties>
</WebElementEntity>