<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>baceabca-21cd-41d4-b764-b4677e5be979</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_participants_pl_kms_meeting_032</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(1) &gt; [class="xl\\:w-\\[396px\\]\\ w-\\[440px\\]\\ xl\\:mx-2\\ mx-12"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nParticipants\n\nPL - KMS Meeting 03251126\n\nSun, March 31 | 10:00 AM\n\n2 Tan Vien\nPhong Hai Le')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#default-carousel &gt;&gt; internal:role=link[name="event_banner.png +100 PL - KMS Meeting 03251126 calendar Sun, March 31 | 10:00"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Participants
        
        PL - KMS Meeting 03251126
        
        Sun, March 31 | 10:00 AM
        
        2 Tan Vien
        Phong Hai Le</value>
        <webElementGuid>5e03467e-4ecb-4d57-ac7f-642d6821fc86</webElementGuid>
    </webElementProperties>
</WebElementEntity>