<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>472eb0b4-afc0-4803-87d4-8371b354f261</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_approved_pl_kms_meeting_mar_23</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nApproved\n\nPL - KMS Meeting Mar 23\n\nStart\n\nSat, Mar 23 | 10:00 AM\n\nEnd\n\nSun, Mar 24 | 05:00 PM\n\n2 Tan Vien')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Approved
        
        PL - KMS Meeting Mar 23
        
        Start
        
        Sat, Mar 23 | 10:00 AM
        
        End
        
        Sun, Mar 24 | 05:00 PM
        
        2 Tan Vien</value>
        <webElementGuid>09ed0195-021b-4230-ad83-98a866fb7e7d</webElementGuid>
    </webElementProperties>
</WebElementEntity>