<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3896b028-0712-4da1-a7ec-e60a0a9e519c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_relay_sparkle_box_diy_matchb</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[4]/div[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid\\ grid-cols-2\\ landingCard\\:grid-cols-4\\ grid-rows-2\\ 2xl\\:grid-cols-4\\ gap-\\[24px\\]\\ lg\\:gap-\\[16px\\]\\ xl\\:gap-\\[20px\\]\\ 2xl\\:gap-\\[24px\\]\\ mt-\\[24px\\]\\ mx-auto\\ transition"] &gt; div:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\n\U0001f419 RELAY - Sparkle Box | DIY Matchbox Fundraiser \u2728\n\nN/A | N/A\n\nCoffee Lounge, Tan Vien Office\nQuyen Vinh Chung\n\nClosed')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 Host check Approved SE-206: Test Edit 1 calendar Sun,"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        🐙 RELAY - Sparkle Box | DIY Matchbox Fundraiser ✨
        
        N/A | N/A
        
        Coffee Lounge, Tan Vien Office
        Quyen Vinh Chung
        
        Closed</value>
        <webElementGuid>ec40d1d7-7e5b-4b03-adb9-ed1b24f47820</webElementGuid>
    </webElementProperties>
</WebElementEntity>