<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2450a80c-96a5-47bb-8a21-c51efbe08279</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_200approveduser create eventfri </name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[7]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="slick-slide slick-active"]:nth-child(7) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+200Approveduser create eventFri, April 05 | 10:00 AMaa')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +200 check"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+200
        
        Approved
        
        user create event
        
        Fri, April 05 | 10:00 AM
        
        aa</value>
        <webElementGuid>eee8f410-af2e-4401-8656-e97b5b578062</webElementGuid>
    </webElementProperties>
</WebElementEntity>