<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>297f5a83-9a8e-42a3-a7c4-be42ef238ded</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_host_approved_copied_of_va_test</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid\\ grid-cols-1\\ landingCard\\:grid-cols-4\\ grid-rows-2\\ 2xl\\:grid-cols-4\\ gap-\\[24px\\]\\ lg\\:gap-\\[16px\\]\\ xl\\:gap-\\[20px\\]\\ 2xl\\:gap-\\[24px\\]\\ mt-\\[24px\\]\\ mx-auto\\ transition"] &gt; div:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nHost\n\nApproved\n\nCopied of VA test ticket timeline #206\n\nSat, April 06 | 10:00 AM\n\nHCMC\nAnh Nhat Van Duong')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 check Approved Copied of VA test ticket timeline #206"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Host
        
        Approved
        
        Copied of VA test ticket timeline #206
        
        Sat, April 06 | 10:00 AM
        
        HCMC
        Anh Nhat Van Duong</value>
        <webElementGuid>1479594f-510a-4569-99d7-db2839f6c020</webElementGuid>
    </webElementProperties>
</WebElementEntity>