<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f88ad5df-a1e1-4c17-b20e-de11d77c0a58</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_host_happy_day_in_december_n_a</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[4]/div[2]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-child(3) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nHost\n\nHappy Day in December\n\nN/A | N/A\n\nKMS Technology 2 Tan Vien\nAnh Nhat Van Duong\n\nClosed')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 Host Happen 1 calendar Thu, March 28 | 10:00 AM Happen 1"i] &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Host
        
        Happy Day in December
        
        N/A | N/A
        
        KMS Technology 2 Tan Vien
        Anh Nhat Van Duong
        
        Closed</value>
        <webElementGuid>ec40d1d7-7e5b-4b03-adb9-ed1b24f47820</webElementGuid>
    </webElementProperties>
</WebElementEntity>