<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a9576474-2cbc-4fd8-96c1-289865eb6743</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100approvedcopied of true test 05</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[4]/div[2]/div[6]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-child(6) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100ApprovedCopied of true test 05Sat, April 13 | 10:00 AMaa')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 check Approved Copied of true test 05 calendar Sat, April"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Approved
        
        Copied of true test 05
        
        Sat, April 13 | 10:00 AM
        
        aa</value>
        <webElementGuid>eee8f410-af2e-4401-8656-e97b5b578062</webElementGuid>
    </webElementProperties>
</WebElementEntity>