<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a37b7dfd-76de-4a34-85bc-a07be5e95ec4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_300123 draftwed april 10  1000 a</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[4]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid grid-cols-1 landingCard:grid-cols-4 grid-rows-2 2xl:grid-cols-4 gap-[24px] lg:gap-[16px] xl:gap-[20px] 2xl:gap-[24px] mt-[24px] mx-auto transition"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+300123 DraftWed, April 10 | 10:00 AM123 DraftThy Thi Anh Phung')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +300 123"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+300
        
        123 Draft
        
        Wed, April 10 | 10:00 AM
        
        123 Draft
        Thy Thi Anh Phung</value>
        <webElementGuid>bd0ce7dd-a0f4-441f-a784-65e062094520</webElementGuid>
    </webElementProperties>
</WebElementEntity>