<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fcb97bc8-50f8-4e26-bf56-bf71e5fb72b0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_approved_long_location_start_th</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nApproved\n\nLong Location\n\nStart\n\nThu, Mar 14 | 12:00 AM\n\nEnd\n\nSat, Mar 16 | 11:59 PM\n\nLong Location Long Location Long Location Long Location Long Location Long Location Long Location')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Approved
        
        Long Location
        
        Start
        
        Thu, Mar 14 | 12:00 AM
        
        End
        
        Sat, Mar 16 | 11:59 PM
        
        Long Location Long Location Long Location Long Location Long Location Long Location Long Location</value>
        <webElementGuid>09ed0195-021b-4230-ad83-98a866fb7e7d</webElementGuid>
    </webElementProperties>
</WebElementEntity>