<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>752ff666-ab63-4d10-bd73-63e0d4cb0f92</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_approved_chuchu_sat_april_06</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nApproved\n\nChuchu\n\nSat, April 06 | 10:00 AM\n\nHCMC\nAnh Nhat Van Duong')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 check Approved Chuchu calendar Sat, April 06 | 10:00 AM"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Approved
        
        Chuchu
        
        Sat, April 06 | 10:00 AM
        
        HCMC
        Anh Nhat Van Duong</value>
        <webElementGuid>5e03467e-4ecb-4d57-ac7f-642d6821fc86</webElementGuid>
    </webElementProperties>
</WebElementEntity>