<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>06106d8d-fc8a-4f84-9080-78abf96a352f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_100_participants_approved_test_bug_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[6]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="slick-slide\\ slick-active"]:nth-child(6) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100\n\nParticipants\n\nApproved\n\ntest bug 229\n\nStart\n\nFri, Mar 01 | 03:00 PM\n\nEnd\n\nWed, Mar 20 | 08:00 PM\n\nabc')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=link[name=\\"event_banner.png +100 Participants check Approved test bug 229 calendar Start\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Participants
        
        Approved
        
        test bug 229
        
        Start
        
        Fri, Mar 01 | 03:00 PM
        
        End
        
        Wed, Mar 20 | 08:00 PM
        
        abc</value>
        <webElementGuid>f41dade5-b828-439c-805f-593f4882b461</webElementGuid>
    </webElementProperties>
</WebElementEntity>