<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>16e9cf7e-fe87-48e9-9322-1cf4501eaec0</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex justify-center items-center"] [class="ant-input ant-input-lg css-dqh9qm"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=dialog &gt;&gt; internal:attr=[placeholder="Search"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>1c6fac0c-3300-4e81-9213-85528144cb1b</webElementGuid>
    </webElementProperties>
</WebElementEntity>