<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5f5b1009-4113-4edd-b90a-67c51ee21ea4</elementGuidId>
    <imagePath></imagePath>
    <name>input_addAnumber</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[4]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid grid-cols-1 landingCard:grid-cols-4 grid-rows-2 2xl:grid-cols-4 gap-[24px] lg:gap-[16px] xl:gap-[20px] 2xl:gap-[24px] mt-[24px] mx-auto transition"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100test x20000N/A | N/A123Closed')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +100 test"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        test x20000
        
        N/A | N/A
        
        123
        
        Closed</value>
        <webElementGuid>b718ad1d-efc7-4859-94b4-787b53e55011</webElementGuid>
    </webElementProperties>
</WebElementEntity>