<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1940a674-b207-4dca-96f2-902376031a7c</elementGuidId>
    <imagePath></imagePath>
    <name>input_nameIdemailProject</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-sm w-full h-10 p-2 font-body bg-white rounded-md border border-neutral-300 outline-none"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Name,ID, Email, Project (*)"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>b718ad1d-efc7-4859-94b4-787b53e55011</webElementGuid>
    </webElementProperties>
</WebElementEntity>