<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f54a5d68-5f32-4c03-b2d8-39a0f605a54d</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/ul[1]/li[6]/span[1]/div[1]/span[1]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-popover-open flex"] [class="ant-checkbox-input"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Event I Register"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>2e64e2f8-b9de-4ed1-9691-142e3842a3b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>