<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>78bed1a6-65bf-45c2-81ae-40bf451a81c0</elementGuidId>
    <imagePath></imagePath>
    <name>link_eventBanner400Host</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid grid-cols-1 landingCard:grid-cols-4 grid-rows-2 2xl:grid-cols-4 gap-[24px] lg:gap-[16px] xl:gap-[20px] 2xl:gap-[24px] mt-[24px] mx-auto transition"] &gt; div:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+400HostTEST PARTICIPANTS TABLE WITH CUSTOM FIELDSTue, May 21 | 10:00 AMhcmOther OrganizationClosed')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +400 Host"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+400
        
        Host
        
        TEST PARTICIPANTS TABLE WITH CUSTOM FIELDS
        
        Tue, May 21 | 10:00 AM
        
        hcm
        Other Organization
        
        Closed</value>
        <webElementGuid>b718ad1d-efc7-4859-94b4-787b53e55011</webElementGuid>
    </webElementProperties>
</WebElementEntity>