<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>215bd4a0-ff5f-426c-940c-dab55226e8f0</elementGuidId>
    <imagePath></imagePath>
    <name>link_eventBanner100</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="xl:w-[396px] w-[440px] xl:mx-2 mx-12"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+100ParticipantsApprovedVA to test #316Wed, May 29 | 10:00 AMHCMC')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#default-carousel &gt;&gt; internal:role=link[name="event_banner.png +100"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+100
        
        Participants
        
        Approved
        
        VA to test #316
        
        Wed, May 29 | 10:00 AM
        
        HCMC</value>
        <webElementGuid>5c9d1e57-acc7-4683-849f-7197d2fb4835</webElementGuid>
    </webElementProperties>
</WebElementEntity>