<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>24b58ec7-4612-49e1-9be1-b1237bf95719</elementGuidId>
    <imagePath></imagePath>
    <name>link_eventBanner200HostApprovedTestEventy1i12_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[3]/div[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'+200HostApprovedtest eventy1i12Fri, May 31 | 10:00 AMhcmKMS Technology')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="event_banner.png +200 Host"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+200
        
        Host
        
        Approved
        
        test eventy1i12
        
        Fri, May 31 | 10:00 AM
        
        hcm
        KMS Technology</value>
        <webElementGuid>b718ad1d-efc7-4859-94b4-787b53e55011</webElementGuid>
    </webElementProperties>
</WebElementEntity>