<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dee323de-afa9-47f6-9878-cb5de1a06cf0</elementGuidId>
    <imagePath></imagePath>
    <name>section_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="py-[40px] min-h-[1052px]"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Published EventsEvent I Co-host+100Co-HostCopied of test notiN/A | N/AabcClosed"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>