<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e42e73f2-a79d-4229-be70-da3d186c6d27</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_11</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hover:font-bold hover:cursor-pointer hover:text-[#26A9E0] text-[#26A9E0] border-b-[3px] py-1 px-2 border-[#26A9E0] font-bold"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span &gt;&gt; internal:has-text="Events"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>