<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4632cdbf-2654-46b4-92bc-8d9948f35c28</elementGuidId>
    <imagePath></imagePath>
    <name>span_close</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]/span[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="anticon anticon-close"] &gt; svg</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="close"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>