<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8400d726-c2cb-4c52-aaa4-a9fcded279c0</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/ul[1]/li[1]/span[1]/div[1]/label[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-dropdown-menu-item ant-dropdown-menu-item-active ant-dropdown-menu-item-disabled ant-dropdown-menu-item-only-child"] [class="ant-checkbox-wrapper ant-checkbox-wrapper-checked w-full css-dqh9qm"] &gt; span:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=menu &gt;&gt; internal:text="All"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>