<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>874a0958-0956-4007-bae0-3e0ecfa67f9f</elementGuidId>
    <imagePath></imagePath>
    <name>svg_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/section[1]/div[1]/div[1]/button[1]/span[1]/span[1]/svg[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="anticon\\ anticon-setting\\ scale-150"] &gt; svg</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="setting"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>