<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ede113e8-9abb-46a3-b7cc-d36934b9eb78</elementGuidId>
    <imagePath></imagePath>
    <name>svg_flat</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/table[1]/thead[1]/tr[1]/th[7]/div[1]/a[1]/button[1]/svg[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="rounded-md\\ h-\\[25px\\]\\ \\ hover\\:bg-\\[\\#d0d1d6\\]\\ flex\\ flex-row\\ items-center\\ \\ text-white\\ font-medium\\ p-1\\ cursor-pointer"] &gt; #Flat</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'Flat')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=columnheader[name="Add New"i] &gt;&gt; internal:role=link &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>Flat</value>
        <webElementGuid>43f5db58-92d4-4e71-a2d5-240c4ea17192</webElementGuid>
    </webElementProperties>
</WebElementEntity>