<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe92d517-6e8f-43e3-a676-3be4f362975d</elementGuidId>
    <imagePath></imagePath>
    <name>span_all341</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/ul[1]/li[1]/span[1]/div[1]/label[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-dropdown-menu-item ant-dropdown-menu-item-disabled ant-dropdown-menu-item-only-child"]:nth-child(1) [class="ant-checkbox-wrapper ant-checkbox-wrapper-checked w-full css-11eyywd"] &gt; span:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=menu &gt;&gt; internal:text="All (341)"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>