<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3c3b6197-616c-46fc-8993-20f675998a32</elementGuidId>
    <imagePath></imagePath>
    <name>button_next</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[4]/button[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-btn css-dqh9qm ant-btn-primary bg-[#27AAE1] flex justify-center items-center gap-2 px-2"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Next')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Next"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Next</value>
        <webElementGuid>b718ad1d-efc7-4859-94b4-787b53e55011</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>b718ad1d-efc7-4859-94b4-787b53e55011</webElementGuid>
    </webElementProperties>
</WebElementEntity>