<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e6eabb7-73b2-4003-b897-afd435b17410</elementGuidId>
    <imagePath></imagePath>
    <name>button_back</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-btn css-dqh9qm ant-btn-primary bg-gray-500 hover:!bg-gray-400 text-white flex justify-center items-center gap-2 px-2"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Back')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Back"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Back</value>
        <webElementGuid>1c6fac0c-3300-4e81-9213-85528144cb1b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>1c6fac0c-3300-4e81-9213-85528144cb1b</webElementGuid>
    </webElementProperties>
</WebElementEntity>