<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>44570511-620c-4c72-8e20-452b93709b8e</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/form[1]/div[1]/div[1]/div[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="grid md:grid-cols-1 lg:grid-cols-2 grid-rows-4 gap-5 w-full"] &gt; div:nth-child(4)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text=/^Happen Time$/ &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>