<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a2fd87bc-ea49-484b-83cc-3981a3c1e5ef</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/aside[1]/div[1]/ul[1]/li[2]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-menu-item\\ ant-menu-item-active\\ py-6\\ text-lg\\ "] &gt; [class="ant-menu-title-content"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Notification"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>