<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>32114971-c095-4bba-83a7-6a4cc5e130de</elementGuidId>
    <imagePath></imagePath>
    <name>svg_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[2]/span[1]/svg[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-steps-item\\ ant-steps-item-finish\\ ant-steps-item-custom"]:nth-child(4) svg</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=button[name=\\"Agenda\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>